/*
 * Copyright (C) 2026 Stanislav Georgiev
 * https://github.com/slaviboy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Regenerates src/styles/fonts.css and src/text/fonts.generated.json from the
 * @fontsource packages actually installed. Run after adding or removing a family:
 *
 *   node scripts/gen-fonts.mjs
 *
 * Only latin subsets are declared — that is what keeps each face 15-25KB.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'

/**
 * Repeated into the generated file, so regenerating does not strip the licence
 * header every other source file carries.
 */
const LICENCE = `/*
 * Copyright (C) 2026 Stanislav Georgiev
 * https://github.com/slaviboy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

`

const FAMILIES = [
  ['inter', 'Inter', 'sans'], ['roboto', 'Roboto', 'sans'], ['open-sans', 'Open Sans', 'sans'],
  ['lato', 'Lato', 'sans'], ['montserrat', 'Montserrat', 'sans'], ['poppins', 'Poppins', 'sans'],
  ['raleway', 'Raleway', 'sans'], ['nunito', 'Nunito', 'sans'], ['work-sans', 'Work Sans', 'sans'],
  ['dm-sans', 'DM Sans', 'sans'], ['oswald', 'Oswald', 'display'],
  ['playfair-display', 'Playfair Display', 'serif'], ['merriweather', 'Merriweather', 'serif'],
  ['lora', 'Lora', 'serif'], ['libre-baskerville', 'Libre Baskerville', 'serif'],
  ['roboto-mono', 'Roboto Mono', 'mono'], ['jetbrains-mono', 'JetBrains Mono', 'mono'],
  ['source-code-pro', 'Source Code Pro', 'mono'],
]
const WEIGHTS = [300, 400, 500, 600, 700]

const imports = []
const meta = []
for (const [pkg, family, category] of FAMILIES) {
  const base = `node_modules/@fontsource/${pkg}`
  if (!existsSync(base)) { console.warn('missing package', pkg); continue }
  const weights = [], italics = []
  for (const w of WEIGHTS) {
    if (existsSync(`${base}/latin-${w}.css`)) { imports.push(`import '@fontsource/${pkg}/latin-${w}.css'`); weights.push(w) }
    if (existsSync(`${base}/latin-${w}-italic.css`)) { imports.push(`import '@fontsource/${pkg}/latin-${w}-italic.css'`); italics.push(w) }
  }
  if (weights.length) meta.push({ pkg, family, category, weights, italics })
}

mkdirSync('src/styles', { recursive: true })
writeFileSync('src/styles/fonts.ts',
  LICENCE +
  `/**\n` +
  ` * Bundled open-source Google fonts, self-hosted via @fontsource.\n` +
  ` * Generated by scripts/gen-fonts.mjs - do not edit by hand.\n` +
  ` *\n` +
  ` * These are @font-face DECLARATIONS only. A browser does not fetch a woff2\n` +
  ` * until a rendered element actually uses that family, so declaring every face\n` +
  ` * costs a few KB of CSS, not megabytes of fonts. The service worker precaches\n` +
  ` * the woff2 files, so every family stays available with no network.\n` +
  ` *\n` +
  ` * Imported as JS modules rather than via CSS @import so each stylesheet passes\n` +
  ` * through Vite's module graph - which is what lets the build plugin strip the\n` +
  ` * redundant .woff fallback. Vite inlines CSS @import inside its own CSS plugin,\n` +
  ` * where transform hooks never see it.\n` +
  ` *\n` +
  ` * Latin subset only, which is what keeps each face around 15-25KB.\n` +
  ` */\n\n` +
  imports.join('\n') + '\n')
writeFileSync('src/text/fonts.generated.json', JSON.stringify(meta, null, 2) + '\n')
console.log(`${meta.length} families, ${imports.length} faces`)
